tutorials4j:
  cache:
    named:
      defaults:
        timeToLive: 20s
        cacheNullValues: false
        enable-statistics: true
      caches:
        users:
          timeToLive: 10s
          cacheNullValues: false

