tutorials4j:
  tenant:
    datasource:
      strategy: database
      jdbc:
        demo1:
          url: jdbc:mysql://localhost:3306/demo1?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver

