spring:
  profiles:
#    active: request-logging
#    active: xss
#    active: annotation
#    active: signature
#    active: swagger
#    active: google-auth
#    active: cached-body
#    active: trace
    active: client

logging:
  level:
    tutorials4j: DEBUG
#    org.springframework: debug