spring:
  data:
    # Redis 配置
    redis:
      host: localhost # Redis服务器地址
      port: 6379 # Redis端口


tutorials4j:
  cache:
    named:
      defaults:
        timeToLive: 2m
        cacheNullValues: false
        enable-statistics: true
      caches:
        signature:
          timeToLive: 1m
          cacheNullValues: true
          redis:
            keyPrefix: security


  web:
    http:
      cached-body:
        url-patterns: /signature/*
      signature:
        interceptor:
          include-path-patterns: /signature/**
        keys:
          appkey1: appSecret1
          appkey2: appSecret2