spring:
  profiles:
#    active: request-logging
#    active: xss
#    active: annotation
#    active: signature
#    active: swagger
#    active: cached-body
#    active: trace
#    active: client
    active: validation

  thymeleaf:
    cache: false
logging:
  level:
    tutorials4j: TRACE
#    org.springframework: debug