
tutorials4j:
  web:
    cached-body:
      enabled: true
      filter:
        url-patterns: /signature/pay
        name: cachedBodyFilter

    signature:
      enabled: true
      nonce-redis-key-prefix: 'signature:nonce:'
      interceptor:
        include-path-patterns: /signature/pay
      keys:
        appkey1: appSecret1
        appkey2: appSecret2