spring:
  data:
    # Redis 配置
    redis:
      host: localhost # Redis服务器地址
      port: 6379 # Redis端口


tutorials4j:
  cache:
    named:
      defaults:
        timeToLive: 2m
        cacheNullValues: false
        enable-statistics: true
      caches:
        idempotent:
          timeToLive: 3s
          cacheNullValues: false
          redis:
            keyPrefix: 'token:'
        access_limited:
          timeToLive: 5s
          cacheNullValues: true
          redis:
            keyPrefix: 'token:'

  web:
    interceptor:
      idempotent:
        include-path-patterns: /annotation/**
      access-limited:
        include-path-patterns: /annotation/**