spring:
  application:
    name: examples-web

server:
  error:
    include-message: always
    include-binding-errors: always

springdoc:
  api-docs.enabled: true
  use-fqn: true
  swagger-ui:
    enabled: true
    show-extensions: true
    show-common-extensions: true


