tutorials4j:
  web:
    google:
      auth:
        filter:
          url-patterns: /auth/test-filter
        credentials:
          - username: tom
            security-key: T6LFESCGW4QGYX33Z2ZAFNJLAU5JWKO7
          - username: zhangs
            security-key: GP2GM5U4WVNXSPD2Y3WSKZQTMW4TZRYL