###
POST http://localhost:8080/jpa/users
Content-Type: application/json

{
 "name": "张三1",
  "password": "123",
  "email": "123@qq.com",
  "age": 18,
  "sex": "female"
}

###
PUT http://localhost:8080/jpa/users/2052387585426329600
Content-Type: application/json

{
  "name": "张三1"
}

###
DELETE http://localhost:8080/jpa/users/2052387585426329600
Content-Type: application/json

###
GET http://localhost:8080/jpa/users
Content-Type: application/json

###
GET http://localhost:8080/jpa/users/search?name=三
Content-Type: application/json



