###
POST http://localhost:8080/api/users
Content-Type: application/json

{
 "name": "张三1234",
  "password": "123",
"email": "123@qq.com",
  "age": 18,
  "sex": "female"
}

###
PUT http://localhost:8080/api/users/2052404491620646914
Content-Type: application/json

{
  "name": "1张三123"
}

###
DELETE http://localhost:8080/api/users/2052404491620646914
Content-Type: application/json

###
GET http://localhost:8080/api/users
Content-Type: application/json

###
GET http://localhost:8080/api/users?name=1
Content-Type: application/json




