###
POST http://localhost:8080/user-tenant/create
Content-Type: application/json
X-Tenant-Code:DEMO1

{
  "name": "tom"
}

### 指定租户查询： DEMO1
GET http://localhost:8080/user-tenant/1
Content-Type: application/json
X-Tenant-Code:demo1

###
POST http://localhost:8080/user-tenant/create
Content-Type: application/json
X-Tenant-Code:DEFAULT

{
  "name": "kate"
}

### 指定租户查询： DEMO1
GET http://localhost:8080/user-tenant/2
Content-Type: application/json
X-Tenant-Code:DEFAULT

### 多线程： DEMO1
GET http://localhost:8080/user-tenant/asyn/1
Content-Type: application/json
X-Tenant-Code:demo1

###
GET http://localhost:8080/non-tenant/user/1
Content-Type: application/json




