
###
GET http://localhost:8080/redisson/block-non-expire-time
Content-Type: application/json

###
GET http://localhost:8080/redisson/block-expire-time
Content-Type: application/json

###
GET http://localhost:8080/redisson/reentrant-non-expire-time
Content-Type: application/json

###
GET http://localhost:8080/redisson/reentrant-expire-time
Content-Type: application/json

###
GET http://localhost:8080/redis/non-expire-time
Content-Type: application/json

###
GET http://localhost:8080/redis/expire-time
Content-Type: application/json


###
GET http://localhost:8080/local/non-wait-time
Content-Type: application/json

###
GET http://localhost:8080/local/wait-time
Content-Type: application/json


