###
GET http://localhost:8080/order-call/block-auto-renewal
Content-Type: application/json

###
GET http://localhost:8080/order-call/block-fixed-lease
Content-Type: application/json

###
GET http://localhost:8080/order-call/reentrant-auto-renewal
Content-Type: application/json

###
GET http://localhost:8080/order-call/reentrant-fixed-lease
Content-Type: application/json


###
GET http://localhost:8080/order-anno/block-auto-renewal
Content-Type: application/json

###
GET http://localhost:8080/order-anno/block-fixed-lease
Content-Type: application/json

###
GET http://localhost:8080/order-anno/reentrant-auto-renewal
Content-Type: application/json

###
GET http://localhost:8080/order-anno/reentrant-fixed-lease
Content-Type: application/json


