### 获取验证码
GET http://localhost:8080/template/get
Content-Type: application/json

### 校验验证码
GET http://localhost:8080/template/check?key=53e401eb0b5a4bc788fba8472dbba8f1&input=TtUb
Content-Type: application/json


### 计数器
GET http://localhost:8080/template/counter?key=123
Content-Type: application/json

