spring:
  profiles:
#    active: signin
#    active: captchaendpoint
#    active: captchatianaiendpoint
#    active: captchafilter
#    active: crypto-api
#    active: totp
    active: schedule

  data:
    # Redis 配置
    redis:
      host: localhost # Redis服务器地址
      port: 6379 # Redis端口
      database: 2

  datasource:
    url: jdbc:postgresql://localhost:5432/t4j
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true


  thymeleaf:
    cache: false


logging:
  level:
    tutorials4j: DEBUG
#    org.springframework: debug