spring:
  profiles:
#    active: captchaendpoint
#    active: tianaicaptchaendpoint
#    active: captchafilter
#    active: cryptoapi
    active: google-auth


  data:
    # Redis 配置
    redis:
      host: localhost # Redis服务器地址
      port: 6379 # Redis端口
      database: 2



logging:
  level:
    tutorials4j: DEBUG
#    org.springframework: debug