spring:
  profiles:
#    active: signin
#    active: captchaendpoint
#    active: captchatianaiendpoint
#    active: captchafilter
#    active: crypto-api
#    active: totp
    active: schedule

  data:
    # Redis 配置
    redis:
      host: localhost # Redis服务器地址
      port: 6379 # Redis端口
      database: 2

  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true


  thymeleaf:
    cache: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

logging:
  level:
    tutorials4j: TRACE
#    org.springframework: debug