tutorials4j:
  cache:
    named:
      defaults:
        timeToLive: 5m
        cacheNullValues: false
        enable-statistics: false
      caches:
        captcha-behavior:
          timeToLive: 1m
          cacheNullValues: false

  feature:
    captcha-enabled: true
  captcha:
    web:
      enabled: true