<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>yunjiao-source.tutorials4j</groupId>
    <artifactId>tutorials4j</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>

    <name>Tutorials4j</name>
    <description>Java教程</description>
    <url>https://gitee.com/yunjiao-source/tutorials4j</url>

    <licenses>
        <license>
            <name>MIT License</name>
            <url>https://www.opensource.org/licenses/mit-license.php</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <developers>
        <developer>
            <name>杨运交(Yun Jiao)</name>
            <email>1290308475@qq.com</email>
        </developer>
    </developers>

    <modules>
        <module>framework</module>
        <module>springboot3</module>
        <module>springboot4</module>
    </modules>

    <scm>
        <connection>scm:git:git@gitee.com:yunjiao-source/tutorials4j.git</connection>
        <developerConnection>scm:git:ssh://git@//gitee.com/yunjiao-source/tutorials4j.git</developerConnection>
        <url>https://gitee.com/yunjiao-source/tutorials4j</url>
    </scm>

    <issueManagement>
        <system>Gitee</system>
        <url>https://gitee.com/yunjiao-source/tutorials4j/issues</url>
    </issueManagement>

    <properties>
        <revision>0.0.1</revision>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>21</java.version>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <flatten-maven-plugin.version>1.7.2</flatten-maven-plugin.version>
        <maven-compiler-plugin.version>3.14.1</maven-compiler-plugin.version>
        <maven-source-plugin.version>3.3.1</maven-source-plugin.version>
        <spotless-maven-plugin.version>3.4.0</spotless-maven-plugin.version>
        <git-build-hook-maven-plugin.version>3.6.0</git-build-hook-maven-plugin.version>

        <springboot3.version>3.5.13</springboot3.version>
        <springboot4.version>4.0.5</springboot4.version>

        <javafaker.version>1.0.2</javafaker.version>
        <commons-io.version>2.21.0</commons-io.version>
        <commons-text.version>1.14.0</commons-text.version>
        <commons-net.version>3.12.0</commons-net.version>
        <commons-collections4.version>4.4</commons-collections4.version>
        <debezium.version>3.4.2.Final</debezium.version>
        <transmittable-thread-local.version>2.14.5</transmittable-thread-local.version>
        <hutool.version>5.8.38</hutool.version>
        <guava.version>33.1.0-jre</guava.version>
        <zxing-core.version>3.5.4</zxing-core.version>
        <antisamy.version>1.7.5</antisamy.version>
        <mybatis-plus.version>3.5.15</mybatis-plus.version>
        <druid.version>1.2.28</druid.version>
        <p6spy.version>3.9.1</p6spy.version>
        <wechatpay-java.version>0.2.17</wechatpay-java.version>
        <springdoc.version>2.8.17</springdoc.version>
        <redisson.version>4.2.0</redisson.version>
        <resilience4j-retry.version>2.4.0</resilience4j-retry.version>
        <tianai-captcha.version>1.5.5</tianai-captcha.version>
        <uid-core.version>2.2</uid-core.version>
        <googleauth.version>1.5.0</googleauth.version>
        <qrgen.version>1.4</qrgen.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>cc.siyecao.uid</groupId>
                <artifactId>uid-core</artifactId>
                <version>${uid-core.version}</version>
            </dependency>

            <dependency>
                <groupId>org.redisson</groupId>
                <artifactId>redisson-spring-boot-starter</artifactId>
                <version>${redisson.version}</version>
            </dependency>

            <dependency>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi</artifactId>
                <version>${springdoc.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
                <version>${springdoc.version}</version>
            </dependency>

            <dependency>
                <groupId>com.github.wechatpay-apiv3</groupId>
                <artifactId>wechatpay-java</artifactId>
                <version>${wechatpay-java.version}</version>
            </dependency>

            <dependency>
                <groupId>p6spy</groupId>
                <artifactId>p6spy</artifactId>
                <version>${p6spy.version}</version>
            </dependency>

            <dependency>
                <groupId>com.github.javafaker</groupId>
                <artifactId>javafaker</artifactId>
                <version>${javafaker.version}</version>
            </dependency>

            <dependency>
                <groupId>commons-io</groupId>
                <artifactId>commons-io</artifactId>
                <version>${commons-io.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-text</artifactId>
                <version>${commons-text.version}</version>
            </dependency>
            <dependency>
                <groupId>commons-net</groupId>
                <artifactId>commons-net</artifactId>
                <version>${commons-net.version}</version>
            </dependency>

            <!-- debezium -->
            <dependency>
                <groupId>io.debezium</groupId>
                <artifactId>debezium-api</artifactId>
                <version>${debezium.version}</version>
            </dependency>
            <dependency>
                <groupId>io.debezium</groupId>
                <artifactId>debezium-embedded</artifactId>
                <version>${debezium.version}</version>
            </dependency>
            <dependency>
                <groupId>io.debezium</groupId>
                <artifactId>debezium-connector-postgres</artifactId>
                <version>${debezium.version}</version>
            </dependency>

            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>transmittable-thread-local</artifactId>
                <version>${transmittable-thread-local.version}</version>
            </dependency>

            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-collections4</artifactId>
                <version>${commons-collections4.version}</version>
            </dependency>

            <dependency>
                <groupId>com.google.guava</groupId>
                <artifactId>guava</artifactId>
                <version>${guava.version}</version>
            </dependency>
            <dependency>
                <groupId>com.google.zxing</groupId>
                <artifactId>core</artifactId>
                <version>${zxing-core.version}</version>
            </dependency>

            <dependency>
                <groupId>cn.hutool</groupId>
                <artifactId>hutool-all</artifactId>
                <version>${hutool.version}</version>
            </dependency>

            <dependency>
                <groupId>org.owasp.antisamy</groupId>
                <artifactId>antisamy</artifactId>
                <version>${antisamy.version}</version>
            </dependency>

            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-bom</artifactId>
                <version>${mybatis-plus.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>druid</artifactId>
                <version>${druid.version}</version>
            </dependency>

            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>druid-spring-boot-3-starter</artifactId>
                <version>${druid.version}</version>
            </dependency>

            <dependency>
                <groupId>io.github.resilience4j</groupId>
                <artifactId>resilience4j-retry</artifactId>
                <version>${resilience4j-retry.version}</version>
            </dependency>

            <dependency>
                <groupId>cloud.tianai.captcha</groupId>
                <artifactId>tianai-captcha</artifactId>
                <version>${tianai-captcha.version}</version>
            </dependency>

            <dependency>
                <groupId>com.warrenstrange</groupId>
                <artifactId>googleauth</artifactId>
                <version>${googleauth.version}</version>
            </dependency>

            <dependency>
                <groupId>net.glxn</groupId>
                <artifactId>qrgen</artifactId>
                <version>${qrgen.version}</version>
            </dependency>

        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>flatten-maven-plugin</artifactId>
                    <version>${flatten-maven-plugin.version}</version>
                    <configuration>
                        <updatePomFile>true</updatePomFile>
                        <flattenMode>resolveCiFriendliesOnly</flattenMode>
                    </configuration>
                    <executions>
                        <execution>
                            <id>flatten</id>
                            <goals>
                                <goal>flatten</goal>
                            </goals>
                            <phase>process-resources</phase>
                        </execution>
                        <execution>
                            <id>flatten.clean</id>
                            <goals>
                                <goal>clean</goal>
                            </goals>
                            <phase>clean</phase>
                        </execution>
                    </executions>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-source-plugin</artifactId>
                    <version>${maven-source-plugin.version}</version>
                    <executions>
                        <execution>
                            <id>attach-sources</id>
                            <goals>
                                <goal>jar-no-fork</goal>
                            </goals>
                            <phase>package</phase>
                        </execution>
                    </executions>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${maven-compiler-plugin.version}</version>
                </plugin>

                <plugin>
                    <groupId>com.diffplug.spotless</groupId>
                    <artifactId>spotless-maven-plugin</artifactId>
                    <version>${spotless-maven-plugin.version}</version>
                    <configuration>
                        <java>
                            <googleJavaFormat />
                        </java>
                        <pom>
                            <includes>
                                <include>pom.xml</include>
                            </includes>
                            <sortPom>
                                <encoding>UTF-8</encoding>
                                <nrOfIndentSpace>4</nrOfIndentSpace>
                                <keepBlankLines>true</keepBlankLines>
                                <indentBlankLines>false</indentBlankLines>
                                <indentAttribute>schemaLocation</indentAttribute>
                                <spaceBeforeCloseEmptyElement>true</spaceBeforeCloseEmptyElement>
                            </sortPom>
                        </pom>
                    </configuration>
                    <executions>
                        <execution>
                            <goals>
                                <goal>check</goal>
                            </goals>
                            <phase>compile</phase>
                        </execution>
                    </executions>
                </plugin>

                <plugin>
                    <groupId>com.rudikershaw.gitbuildhook</groupId>
                    <artifactId>git-build-hook-maven-plugin</artifactId>
                    <version>${git-build-hook-maven-plugin.version}</version>
                    <configuration>
                        <!-- 把项目钩子目录设为 git 默认 hooks -->
                        <gitConfig>
                            <core.hooksPath>config/githooks/</core.hooksPath>
                        </gitConfig>
                        <!-- 自动安装钩子 -->
                        <installHooks>
                            <pre-commit>config/githooks/pre-commit</pre-commit>
                            <pre-push>.config/githooks/pre-push</pre-push>
                        </installHooks>
                    </configuration>
                    <executions>
                        <execution>
                            <goals>
                                <goal>configure</goal>
                            </goals>
                            <!-- 每次构建都确保钩子配置生效 -->
                            <phase>initialize</phase>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </pluginManagement>

        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>flatten-maven-plugin</artifactId>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
            </plugin>

            <plugin>
                <groupId>com.diffplug.spotless</groupId>
                <artifactId>spotless-maven-plugin</artifactId>
            </plugin>

            <plugin>
                <groupId>com.rudikershaw.gitbuildhook</groupId>
                <artifactId>git-build-hook-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
