

tutorials4j:
  cache:
    named:
      defaults:
        timeToLive: 40s
        cacheNullValues: false
        enable-statistics: true
      caches:
        users:
          timeToLive: 20s
          cacheNullValues: false





