
tutorials4j:
  cache:
    named:
      defaults:
        timeToLive: 2m
        cacheNullValues: false
        enable-statistics: true
        redis:
          cache-prefix: 'share:'
      caches:
        captcha:
          timeToLive: 10s
          cacheNullValues: false
        counter:
          timeToLive: 20s
          cacheNullValues: false
          redis:
            cache-prefix: 'share1:share1:'





