

tutorials4j:
  cache:
    redis:
      named-caches:
        users:
          timeToLive: 30s
          cacheNullValues: false
          keyPrefix: user
          useKeyPrefix: true
        orders:
          timeToLive: 60s
          cacheNullValues: true
          keyPrefix: order
          useKeyPrefix: false

