
tutorials4j:
  cache:
    named:
      defaults:
        timeToLive: 2m
        cacheNullValues: false
        enable-statistics: true
        redis:
          key-prefix: share
      caches:
        captcha:
          timeToLive: 10s
          cacheNullValues: false
        counter:
          timeToLive: 20s
          cacheNullValues: false





