
tutorials4j:
  cache:
    named:
      defaults:
        timeToLive: 2m
        cacheNullValues: false
        enable-statistics: false
      caches:
        users:
          timeToLive: 10s
          cacheNullValues: false
          redis:
            cache-prefix: user
        orders:
          timeToLive: 20s
          cacheNullValues: true
          redis:
            cache-prefix: 'order:'


