
logging:
  level:
    org.springframework.cache: debug

tutorials4j:
  cache:
    named:
      defaults:
        timeToLive: 10s
        cacheNullValues: false
        enable-statistics: true
        redis:
          cache-prefix: 'share:'
      caches:
        users:
          timeToLive: 20s
          cacheNullValues: false
          redis:
            cache-prefix: 'user:'





