###
GET http://localhost:8080/redis/cacheable/users?id=1
Content-Type: application/json

###
GET http://localhost:8080/redis/cacheable/orders?id=1
Content-Type: application/json

###
GET http://localhost:8080/redis/cacheable/cars?id=1
Content-Type: application/json

### 租户
GET http://localhost:8080/redis/cacheable/tenant-users?id=1
Content-Type: application/json

### 查看全部缓存
GET http://localhost:8080/actuator/caches
Content-Type: application/json

### 查看特定缓存
GET http://localhost:8080/actuator/caches/users
Content-Type: application/json

### 查看具体指标
GET http://localhost:8080/actuator/metrics/cache.gets
Content-Type: application/json

