### 获取验证码
GET http://localhost:8080/template/get
Content-Type: application/json

### 校验验证码
GET http://localhost:8080/template/check?key=55541dcd6ab04af8881108a5645eebe5&input=zGBI
Content-Type: application/json


### 计数器
GET http://localhost:8080/template/counter?key=123
Content-Type: application/json

