###
GET http://localhost:8080/test-exec?concurrentRequests=70&durationSeconds=300

###
GET http://localhost:8080/api/pool/status
Content-Type: application/json

###
GET http://localhost:8080/api/pool/metrics/history
Content-Type: application/json

###
GET http://localhost:8080/api/pool/config
Content-Type: application/json