###
POST http://localhost:8080/cached-request/cached
Content-Type: text/plain

{
"Hello, CachedBody!"
}

###
POST http://localhost:8080/cached-request/non-cached
Content-Type: text/plain

{
"Hello, CachedBody!"
}



