###
GET http://localhost:8080/request-logging/hello?name=张三
Content-Type: application/json

###
POST http://localhost:8080/request-logging/user
Content-Type: application/json

{
"username": "张三",
  "email": "张三@qq.com"
}

### 此请求不在filter范围内
GET http://localhost:8080/demo/get
Content-Type: application/json



