###
GET http://localhost:8080/security/idempotent
Content-Type: application/json

###
GET http://localhost:8080/security/access-limited
Content-Type: application/json

###
GET http://localhost:8080/security/xss/safe?name=<script>alert('XSS')</script>

###
GET http://localhost:8080/security/xss/unsafe?name=<script>alert('XSS')</script>

### 此请求不在filter范围内
GET http://localhost:8080/demo/get
Content-Type: application/json







