###
GET http://localhost:8080/swagger-ui.html
Accept: text/html

###
GET http://localhost:8080/v3/api-docs
Content-Type: application/json

###
GET http://localhost:8080/v3/api-docs.yaml
Content-Type: application/x-yaml