###
GET http://localhost:8080/trace/common/get
Content-Type: application/json

###
GET http://localhost:8080/trace/common/exception
Content-Type: application/json

###
GET http://localhost:8080/trace/mono/get1
Content-Type: application/json

###
GET http://localhost:8080/trace/mono/get2
Content-Type: application/json

###
GET http://localhost:8080/trace/mono/exception
Content-Type: application/json

###
GET http://localhost:8080/trace/non-logger
Content-Type: application/json

### 此请求不在filter范围内
GET http://localhost:8080/demo/get
Content-Type: application/json




