
###
GET http://localhost:8080/xss/param?content=<script>alert('XSS')</script>Hello
Content-Type: application/json

###
POST http://localhost:8080/xss/json
Content-Type: application/json


{
  "username": "<img src=x onerror=alert(1)>John",
  "comment": "Nice <b>product</b> &lt;script&gt;"
}

### 此请求不在filter范围内
GET http://localhost:8080/demo/get
Content-Type: application/json
