<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>yunjiao-source.tutorials4j.framework</groupId>
        <artifactId>framework-feature</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>feature-schedule</artifactId>
    <packaging>jar</packaging>
    <name>Feature :: Schedule</name>
    <description>定时任务功能模块</description>

    <dependencies>
        <dependency>
            <groupId>yunjiao-source.tutorials4j.framework</groupId>
            <artifactId>feature-core</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>yunjiao-source.tutorials4j.framework</groupId>
            <artifactId>schedule-core</artifactId>
            <version>${revision}</version>
        </dependency>

    </dependencies>

</project>
