package tutorials4j.framework.common.core;

/**
 * 基础属性配置常量
 *
 * @author Yun Jiao
 */
public interface PropertiesConsts {
  String PROPERTY_ENABLED = "enabled";
  String PROPERTY_PREFIX_SPRING = "spring";
  String PROPERTY_PREFIX_TUTORIALS4J = "tutorials4j";

  /* ---------- 自定义配置属性 ---------- */
  /** common */
  String PROPERTY_PREFIX_COMMON = PROPERTY_PREFIX_TUTORIALS4J + ".common";

  String PROPERTY_PREFIX_COMMON_UID = PROPERTY_PREFIX_COMMON + ".uid";

  /** assembly */
  String PROPERTY_PREFIX_ASSEMBLY = PROPERTY_PREFIX_TUTORIALS4J + ".assembly";

  /** schedule */
  String PROPERTY_PREFIX_SCHEDULE = PROPERTY_PREFIX_TUTORIALS4J + ".schedule";

  String PROPERTY_PREFIX_SCHEDULE_POWERJOB_WORKER = PROPERTY_PREFIX_SCHEDULE + ".powerjob.worker";

  String PROPERTY_PREFIX_SCHEDULE_XXL_JOB = PROPERTY_PREFIX_SCHEDULE + ".xxl-job";

  /** cache */
  String PROPERTY_PREFIX_CACHE = PROPERTY_PREFIX_TUTORIALS4J + ".cache";

  String PROPERTY_PREFIX_CACHE_LOCK = PROPERTY_PREFIX_TUTORIALS4J + ".lock";

  String PROPERTY_PREFIX_CACHE_NAMED = PROPERTY_PREFIX_CACHE + ".named";

  /** crypto */
  String PROPERTY_PREFIX_CRYPTO = PROPERTY_PREFIX_TUTORIALS4J + ".crypto";

  /** captcha */
  String PROPERTY_PREFIX_CAPTCHA = PROPERTY_PREFIX_TUTORIALS4J + ".captcha";

  String PROPERTY_PREFIX_CAPTCHA_HUTOOL = PROPERTY_PREFIX_CAPTCHA + ".hutool";

  String PROPERTY_PREFIX_CAPTCHA_TIANAI = PROPERTY_PREFIX_CAPTCHA + ".tianai";

  String PROPERTY_PREFIX_CAPTCHA_WEB = PROPERTY_PREFIX_CAPTCHA + ".web";

  /** web */
  String PROPERTY_PREFIX_WEB = PROPERTY_PREFIX_TUTORIALS4J + ".web";

  String PROPERTY_PREFIX_WEB_TRACE = PROPERTY_PREFIX_WEB + ".trace";

  String PROPERTY_PREFIX_WEB_XSS = PROPERTY_PREFIX_WEB + ".xss";

  String PROPERTY_PREFIX_WEB_SIGNATURE = PROPERTY_PREFIX_WEB + ".signature";

  String PROPERTY_PREFIX_WEB_TOTP = PROPERTY_PREFIX_WEB + ".totp";

  String PROPERTY_PREFIX_WEB_CACHAED_BODY = PROPERTY_PREFIX_WEB + ".cached-body";

  String PROPERTY_PREFIX_WEB_REQUEST_LOGGING = PROPERTY_PREFIX_WEB + ".request-logging";

  String PROPERTY_PREFIX_WEB_CLIENT = PROPERTY_PREFIX_WEB + ".client";

  String PROPERTY_PREFIX_WEB_SECURITY = PROPERTY_PREFIX_WEB + ".security";

  /** data */
  String PROPERTY_PREFIX_DATA = PROPERTY_PREFIX_TUTORIALS4J + ".data";

  String PROPERTY_PREFIX_DATA_MYBATIS_PLUS = PROPERTY_PREFIX_DATA + ".mybatis-plus";

  String PROPERTY_PREFIX_DATA_HIBERNATE = PROPERTY_PREFIX_DATA + ".hibernate";

  /** tenant */
  String PROPERTY_PREFIX_TENANT = PROPERTY_PREFIX_TUTORIALS4J + ".tenant";

  /** feature */
  String PROPERTY_PREFIX_FEATURE = PROPERTY_PREFIX_TUTORIALS4J + ".feature";

  String PROPERTY_PREFIX_FEATURE_SIGN_IN = PROPERTY_PREFIX_FEATURE + ".sign-in";

  String PROPERTY_PREFIX_FEATURE_CAPTCHA = PROPERTY_PREFIX_FEATURE + ".captcha";
}
