spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      # 初始配置
      minimum-idle: 5
      maximum-pool-size: 20
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update


tutorials4j:
  data:
    tenant:
      path-patterns: /user-tenant/*
      type: table


logging:
  level:
    tutorials4j: DEBUG