spring:
  datasource:
    driver-class-name: ${env.datasource.driver-class-name:com.mysql.cj.jdbc.Driver}
    url: jdbc:mysql://${env.datasource.url:127.0.0.1}:${env.datasource.port:3306}/tutorials4j?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: ${env.datasource.username:root}
    password: ${env.datasource.password:123456}
    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000