env:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 127.0.0.1
    port: 3306
    username: root
    password: root

  redis:
    host: localhost
    port: 6379
    database: 4
    username: admin
    password: admin

  include-urls: /**
  exclude-urls: /favicon.ico,/.well-known/**,/webjars/**,/swagger-ui/*,/v3/api-docs,/v3/api-docs/swagger-config,/css/*,/js/*,/images/*,/openapi/*

