tutorials4j:
  toolkit:
    security:
      sa-token:
        filter:
          include-urls: ${env.include-urls}
          exclude-urls: ${env.exclude-urls}
          auth-strategies:
            - logging
            - blockUrls
            - whiteUrls
            - checkLogin
          before-auth-strategies:
#            - cors
            - optionsMethod

        interceptor:
          #          include-path-patterns: ${env.exclude-urls}
          exclude-path-patterns: ${env.include-urls}
          handle-annotation: false
          param-functions:
            - checkLogin