tutorials4j:
  toolkit:
    security:
      sa-token:
        filter:
          include-urls:
            - /**
          exclude-urls:
            - /favicon.ico
            - /.well-known/**
            - /webjars/**
            - /sa-res/**
            - /oauth2/**