tutorials4j:
  toolkit:
    security:
      sa-token:
        filter:
          include-urls:
            - /**
          exclude-urls:
            - /favicon.ico
            - /.well-known/**
            - /webjars/**
            - /swagger-ui/*
            - /v3/api-docs
            - /v3/api-docs/swagger-config
            - /sa-res/**
            - /accounts/*