
### pdf
GET http://localhost:8080/cursorUsers/export/pdf
Content-Type: application/octet-stream

### xml
GET http://localhost:8080/cursorUsers/export/xml
Content-Type: application/octet-stream

### html
GET http://localhost:8080/cursorUsers/export/html
Content-Type: application/octet-stream