###
GET http://localhost:8080/mybatisUser?mybatisUser=666,中国cn
Content-Type: application/json

###
POST http://localhost:8080/mybatisUser?mybatisUser=666,中国cn
Content-Type: application/x-www-form-urlencoded

###
GET http://localhost:8080/mybatisUser-wrapper?age=16&mybatisUser=666,中国cn
Content-Type: application/json

###
POST http://localhost:8080/mybatisUser-wrapper
Content-Type: application/x-www-form-urlencoded

mybatisUser=666,中国cn&age=16

