###
GET http://localhost:8080/timed
Accept: text/plain

###
GET http://localhost:8080/counted/1
Accept: text/plain

###
GET http://localhost:8080/counted/2
Accept: text/plain

###
GET http://localhost:8080/actuator/prometheus
Accept: text/plain

###
GET http://localhost:8080/actuator/metrics/demo.controller.timed
Accept: application/json


###
GET http://localhost:8080/actuator/metrics/demo.service.timed
Accept: application/json

###
GET http://localhost:8080/actuator/metrics/demo.controller.counted
Accept: application/json


###
GET http://localhost:8080/actuator/metrics/demo.service.counted
Accept: application/json