server:
  port: 9101

spring:
  profiles:
    active: simple

  datasource:
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      # 初始配置
      minimum-idle: 2
      maximum-pool-size: 5
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

  data:
    # Redis 配置
    redis:
      host: localhost # Redis服务器地址
      port: 6379 # Redis端口
      database: 4

logging:
  level:
    tutorials4j: DEBUG
    org.springframework: debug