<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>yunjiao-source.tutorials4j.microservice</groupId>
        <artifactId>microservice</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>microservice-oauth</artifactId>
    <name>MicroService :: OAuth</name>
    <description>鉴权与认证微服务</description>

    <dependencies>
        <dependency>
            <groupId>yunjiao-source.tutorials4j.toolkit</groupId>
            <artifactId>toolkit-security-webmvc</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>yunjiao-source.tutorials4j.feature</groupId>
            <artifactId>feature-oauth-web</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>yunjiao-source.tutorials4j.assembly</groupId>
            <artifactId>assembly-resource-microservice-starter</artifactId>
            <version>${revision}</version>
        </dependency>

        <!-- Sa-Token 权限认证, 在线文档：https://sa-token.com -->
        <dependency>
            <groupId>cn.dev33</groupId>
            <artifactId>sa-token-spring-boot4-starter</artifactId>
        </dependency>

        <!-- Sa-Token OAuth2.0 模块 -->
        <dependency>
            <groupId>cn.dev33</groupId>
            <artifactId>sa-token-oauth2</artifactId>
        </dependency>

        <!-- Sa-Token 整合 RedisTemplate (可选) -->
        <dependency>
            <groupId>cn.dev33</groupId>
            <artifactId>sa-token-redis-template</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-pool2</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-thymeleaf</artifactId>
        </dependency>

        <dependency>
            <groupId>org.webjars</groupId>
            <artifactId>webjars-locator-core</artifactId>
        </dependency>

        <dependency>
            <groupId>org.webjars</groupId>
            <artifactId>bootstrap</artifactId>
        </dependency>
        <dependency>
            <groupId>org.webjars</groupId>
            <artifactId>jquery</artifactId>
        </dependency>
    </dependencies>

</project>
