spring:
  profiles:
#    active: p6spy
#    active: mybatis
#    active: jpa
    active: hibernate-secondlevelcache
  data:
    # Redis 配置
    redis:
      host: localhost # Redis服务器地址
      port: 6379 # Redis端口
      database: 2

  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    druid:
      initial-size: 2
      min-idle: 1
      max-active: 10
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 监控配置
      filters: stat,slf4j
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: 123456
        reset-enable: true
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

logging:
  level:
    tutorials4j: TRACE
#    org.springframework: debug