### 文件上传示例
POST http://localhost:8080/upload-file
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="example.txt"
Content-Type: text/plain

< D:\code\tutorials4j\springboot3\springboot3-ftp-file\src\test\resources\example.txt
--WebAppBoundary--


