tutorials4j:
  oauth:
    api-key-rate-limiter:
      default-limiter:
        max-request-count: 5
        time-window: 1s
      named-limiter:
        demo:
          max-request-count: 5
          time-window: 3s
      interceptor:
        include-path-patterns: /api-key