spring:
  profiles:
#    active: captcha
#    active: annotation
    active: mailtemplate
#    active: httpexchange
#    active: hikariscaler


logging:
  level:
    tutorials4j: DEBUG
#    org.springframework: debug