# mail
spring.mail:
  default-encoding: UTF-8
  host: smtp.qq.com
  username: xxxx@qq.com
  password: ????????
  # from: xxxx@qq.com
  properties.mail.smtp:
    auth: true
    starttls:
      enable: true
      required: true