spring:
  profiles:
#    active: captcha
#    active: annotation
#    active: mailtemplate
#    active: referer
#    active: restresponse
#    active: resourceload
#    active: restversion
#    active: httpexchange
#    active: hikariscaler
#    active: validation
#    active: websocket
#    active: responsebodyemitter
#    active: apicrypto
    active: chainofresponsibility



  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      # 初始配置
      minimum-idle: 5
      maximum-pool-size: 20
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

logging:
  level:
    tutorials4j: DEBUG
#    org.springframework: debug