spring:
  profiles:
#    active: debezium
#    active: ftp
#    active: micrometerannotation
#    active: pay
#    active: qps
#    active: restsignature
#    active: googleauth
    active: jasperreports


  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
logging:
  level:
    tutorials4j: DEBUG
#    org.springframework: debug