
###
GET http://localhost:8080/captcha/create?category=HUTOOL_LINE
Content-Type: application/json

###
POST http://localhost:8080/captcha/check
Content-Type: application/json

{
  "key": "f5ff336a1d004c4da2e659e5177ac702",
  "code": "4XzDr",
  "category": "HUTOOL_LINE"
}


###
GET http://localhost:8080/captcha/create?category=HUTOOL_GIF
Content-Type: application/json

###
GET http://localhost:8080/captcha/create?category=TIANAI_ROTATE
Content-Type: application/json

### hutool验证码页面
GET http://localhost:8080/page/hutool
Accept: text/html

### tianai验证码页面
GET http://localhost:8080/page/tianai-word-image-click
Accept: text/html

### tianai验证码页面
GET http://localhost:8080/page/tianai-rotate
Accept: text/html

### tianai验证码页面-deepseek
GET http://localhost:8080/page/tianai-slider-dp
Accept: text/html

### tianai验证码页面-元宝
GET http://localhost:8080/page/tianai-slider-yb
Accept: text/html

### tianai官方web sdk
GET http://localhost:8080/page/tianai-websdk
Accept: text/html

### 访问保护资源
GET http://localhost:8080/article
Accept: text/plain
X-Captcha-Key: 03511eb349f24369aebe824e9f41f2c7
X-Captcha-Category: HUTOOL_LINE
X-Captcha-Code: BM4zL

