
###
GET http://localhost:8080/captcha/hutool/create?category=HUTOOL_LINE
Content-Type: application/json

###
POST http://localhost:8080/captcha/hutool/check
Content-Type: application/json

{
  "key": "f5ff336a1d004c4da2e659e5177ac702",
  "code": "4XzDr",
  "category": "HUTOOL_LINE"
}


###
GET http://localhost:8080/captcha/hutool/create?category=HUTOOL_GIF
Content-Type: application/json

### 页面
GET http://localhost:8080/page/hutool
Accept: text/html

