<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>yunjiao-source.tutorials4j.framework</groupId>
        <artifactId>framework-captcha</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>captcha-spring-boot-starter</artifactId>
    <packaging>jar</packaging>
    <name>Captcha :: Captcha Spring Boot Starter</name>
    <description>验证码 启动器</description>

    <dependencies>
        <dependency>
            <groupId>yunjiao-source.tutorials4j.framework</groupId>
            <artifactId>web-spring-boot-starter</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>yunjiao-source.tutorials4j.framework</groupId>
            <artifactId>captcha-web</artifactId>
            <version>${revision}</version>
        </dependency>

    </dependencies>
</project>
