<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>yunjiao-source.tutorials4j.framework</groupId>
        <artifactId>framework-oss</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>oss-file-storage-spring</artifactId>
    <packaging>jar</packaging>
    <name>OSS :: Spring File Storage</name>
    <description>对象存储启Spring File Storage模块</description>

    <dependencies>
        <dependency>
            <groupId>yunjiao-source.tutorials4j.framework</groupId>
            <artifactId>oss-core</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>org.dromara.x-file-storage</groupId>
            <artifactId>x-file-storage-spring</artifactId>
        </dependency>

        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-core</artifactId>
            <optional>true</optional>
        </dependency>
    </dependencies>

</project>
