<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>yunjiao-source.tutorials4j.framework</groupId>
        <artifactId>framework</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>framework-examples</artifactId>
    <packaging>pom</packaging>
    <name>Framework :: Examples</name>
    <description>Framework Examples</description>

    <modules>
        <module>examples-common</module>
        <module>examples-cache</module>
        <module>examples-data</module>
        <module>examples-web</module>
        <module>examples-tenant</module>
        <module>examples-captcha</module>
        <module>examples-crypto</module>
        <module>examples-feature</module>
    </modules>

    <dependencies>
        <dependency>
            <groupId>com.github.javafaker</groupId>
            <artifactId>javafaker</artifactId>
        </dependency>
    </dependencies>
</project>
