<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>yunjiao-source.tutorials4j.framework</groupId>
        <artifactId>framework</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>framework-examples</artifactId>
    <packaging>pom</packaging>
    <name>Framework :: Examples</name>
    <description>
        Framework Examples
    </description>

    <modules>
        <module>examples-common-jpa</module>
        <module>examples-web-cached-request-body</module>
        <module>examples-cache-named-redis</module>
        <module>examples-data-hibernate-tenant-db</module>
    </modules>

</project>