tutorials4j.web.http:
    cached-request-body:
      max-content-length: 1MB   # 允许的最大请求体大小
      url-patterns: /demo/cached
      order: -999
      dispatcher-types: REQUEST, FORWARD

logging:
  level:
    tutorials4j: DEBUG