
spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
tenants:
  tenant-a:
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  tenant-b:
    url: jdbc:postgresql://localhost:5432/demo1
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver