spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      schema-locations: classpath:src/main/db/schema-pg.sql
      #data-locations: classpath:db/data-h2.sql
      mode: always



