<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>yunjiao-source.turorials4j</groupId>
        <artifactId>turorials4j</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <groupId>yunjiao-source.turorials4j.springboot3</groupId>
    <artifactId>springboot3</artifactId>
    <packaging>pom</packaging>
    <name>Tutorials4j :: Spring Boot3</name>
    <description>
        Spring Boot3
    </description>

    <modules>
        <module>springboot3-common-jpa</module>
        <module>springboot3-custom-annotation</module>
        <module>springboot3-rest-response</module>
        <module>springboot3-rest-signature</module>
        <module>springboot3-batch-simple</module>
        <module>springboot3-captcha-simple</module>
        <module>springboot3-caffeine-redis</module>
        <module>springboot3-micrometer-annotation</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>3.5.13</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>yunjiao-source.turorials4j.framework</groupId>
                <artifactId>framework-bom</artifactId>
                <version>${revision}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>com.github.javafaker</groupId>
            <artifactId>javafaker</artifactId>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>