<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>yunjiao-source.tutorials4j</groupId>
        <artifactId>tutorials4j</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <groupId>yunjiao-source.tutorials4j.springboot3</groupId>
    <artifactId>springboot3</artifactId>
    <packaging>pom</packaging>
    <name>Tutorials4j :: Spring Boot3</name>
    <description>Spring Boot3</description>

    <modules>
        <module>springboot3-common-jpa</module>
        <module>springboot3-common-mybatis</module>
        <module>springboot3-web</module>
        <module>springboot3-cache</module>
        <module>springboot3-data-orm</module>
        <module>springboot3-data-mongodb</module>
        <module>springboot3-data-redis</module>
        <module>springboot3-data-amqp</module>
        <module>springboot3-webflux</module>
        <module>springboot3-batch</module>
        <module>springboot3-integration</module>
        <module>springboot3-schedule</module>
        <module>springboot3-design-patterns</module>
        <module>springboot3-extension</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${springboot3.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>com.github.javafaker</groupId>
            <artifactId>javafaker</artifactId>
        </dependency>

        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
