<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>yunjiao-source.tutorials4j.framework</groupId>
        <artifactId>framework</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>framework-schedule</artifactId>
    <packaging>pom</packaging>
    <name>Framework :: Schedule</name>
    <description>计划任务模块</description>

    <modules>
        <module>schedule-core</module>
        <module>schedule-redis</module>
        <module>schedule-redisson</module>
        <module>schedule-xxl-job</module>
        <module>schedule-powerjob-worker</module>
        <module>schedule-spring-boot-starter</module>
    </modules>

</project>
