management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    prometheus:
      access: read_only
  metrics:
    enable:
      all: true
  observations:
    annotations:
      enabled: true

