tutorials4j:
  cache:
    named:
      defaults:
        timeToLive: 2m
        cacheNullValues: false
        enable-statistics: true
      caches:
        crypto-request:
          timeToLive: 1m
          cacheNullValues: false
          caffeine:
            expire-after-access: 30s
            initial-capacity: 2
            maximum-size: 5