scrape_configs:
  - job_name: 'microservice-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'localhost:9801'
        labels:
          service: 'microservice-gateway'
          env: 'prod'

  - job_name: 'microservice-demo'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'localhost:9899'
        labels:
          service: 'microservice-demo'
          env: 'prod'