nats:
  spring:
    server: nats://localhost:4222
    username: root
    password: root

spring:
  cloud:
    function:
      definition: sms
    stream:
      bindings:
        # 消息发送通道配置
        sms-out-0:                 # 输出通道名称
          destination: sms-topic   # NATS 中的主题名称
          content-type: application/json
          binder: nats
        # 消息接收通道配置
        sms-in-0:                  # 输入通道名称
          destination: sms-topic   # 需要监听的主题名称
          content-type: application/json
          binder: nats
          group: sms-group         # 消费者组，用于实现负载均衡