tutorials4j:
  message:
    redis:
      queues:
        demo1:
          consumer-group: demo1-group1
          sleep-time-when-exception: 3s
          count-pre-read: 10
          block-timeout: 5s
          retention-time: 2m


