tutorials4j:
  message:
    redis:
      queues:
        sms:
          block-timeout: 5s
          sleep-time-when-exception: 3s
          retry:
            enabled: true
            max-count: 3
            expire-time: 10s
            delay-time: 3s

