###
POST http://localhost:8080/users/create
X-Tenant-Code:DEFAULT
Content-Type: application/json

{
  "name": "张三",
  "email": "张三@qq.com"
}


###
POST http://localhost:8080/users/create
X-Tenant-Code:demo1
Content-Type: application/json

{
  "name": "李四",
  "email": "李四@qq.com"
}


### 指定租户查询
GET http://localhost:8080/users
Content-Type: application/json
X-Tenant-Code:DEFAULT

### 指定租户查询： DEMO1
GET http://localhost:8080/users
Content-Type: application/json
X-Tenant-Code:demo1

### 多线程： DEMO1
GET http://localhost:8080/users/asyn/1
Content-Type: application/json
X-Tenant-Code:demo1xx

### 错误的租户代码，异常
GET http://localhost:8080/users
Content-Type: application/json
X-Tenant-Code:WRONG

### 没有拦截器
GET http://localhost:8080/non-tenant-user
Content-Type: application/json
X-Tenant-Code:DEMO1

### 没有拦截器
GET http://localhost:8080/non-tenant-user/asyn/1
Content-Type: application/json
X-Tenant-Code:DEMO1


### druid数据源页面
GET http://localhost:8080/druid
Accept: text/plain



