###
POST http://localhost:8080/users
X-Tenant-Code:DEFAULT
Content-Type: application/json

{
  "name": "张三1234",
  "password": "123",
  "email": "123@qq.com",
  "age": 18
}

###
GET http://localhost:8080/users
X-Tenant-Code:DEFAULT
Content-Type: application/json

###
GET http://localhost:8080/users/async/2694215804919808
X-Tenant-Code:DEFAULT
Content-Type: application/json

###
POST http://localhost:8080/users
X-Tenant-Code:DEMO1
Content-Type: application/json

{
  "name": "李四1234",
  "password": "123",
  "email": "123@qq.com",
  "age": 18
}

###
GET http://localhost:8080/users
X-Tenant-Code:DEMO1
Content-Type: application/json

###
GET http://localhost:8080//users/async/2053336285883535360
X-Tenant-Code:DEMO1
Content-Type: application/json






