### 没有租户头信息，结果是默认数据
GET http://localhost:8080/user/1
Content-Type: application/json

### 指定租户查询
GET http://localhost:8080/user/1
Content-Type: application/json
X-Tenant-Code:DEFAULT

### 指定租户查询： DEMO1
GET http://localhost:8080/user/1
Content-Type: application/json
X-Tenant-Code:demo1

### 多线程： DEMO1
GET http://localhost:8080/user/asyn/1
Content-Type: application/json
X-Tenant-Code:demo1

### 错误的租户代码，异常
GET http://localhost:8080/user/1
Content-Type: application/json
X-Tenant-Code:WRONG

### 虽然指定租户代码，但是因为没有拦截器，所以是默认数据库数据
GET http://localhost:8080/non-tenant/user/1
Content-Type: application/json
X-Tenant-Code:DEMO1


### druid数据源页面
GET http://localhost:8080/druid
Accept: text/plain



