###
GET http://localhost:8080/web-client/get
Content-Type: application/json

###
GET http://localhost:8080/web-client/get/1
Content-Type: application/json

###
POST http://localhost:8080/web-client/post
Content-Type: application/json





