<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>yunjiao-source.tutorials4j.microservice</groupId>
        <artifactId>microservice</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>microservice-system</artifactId>
    <packaging>pom</packaging>
    <name>MicroService :: System</name>
    <description>系统微服务</description>

    <modules>
        <module>system-model</module>
        <module>system-component</module>
        <module>system-web</module>
        <module>system-server</module>
    </modules>

</project>
