spring:
  profiles:
#    active: simple
#    active: remindtask
    active: dynamiccron


  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

logging:
  level:
    tutorials4j: DEBUG
#    org.springframework: debug