###
GET http://localhost:8080/client/rest-template/get
Content-Type: application/json

###
GET http://localhost:8080/client/rest-template/get/1
Content-Type: application/json

###
GET http://localhost:8080/client/rest-template/get/1
Content-Type: application/json

###
POST http://localhost:8080/client/rest-template/post
Content-Type: application/json




