#spring:
#  rabbitmq:
#    template:
#      allowed-list-patterns:
#        - tutorials4j.springboot3.data.amqp.orderedmessage.OrderMessage

spring:
  rabbitmq:
    listener:
      simple:
        acknowledge-mode: manual   # 关键配置，设置为手动确认