###
GET http://localhost:8080/logger/mybatisUser?userId=user123
Accept: text/plain

###
GET http://localhost:8080/logger/order?orderNo=order123
Accept: text/plain


###
GET http://localhost:8080/need-permission/mybatisUser/query
Accept: text/plain

###
GET http://localhost:8080/need-permission/mybatisUser/add
Accept: text/plain

###
GET http://localhost:8080/need-permission/order/add
Accept: text/plain


###
POST http://localhost:8080/check-param/mybatisUser/save
Content-Type: application/json

{
  "userId": "1"
}