###
GET http://localhost:8080/v1.0/api/cursorUsers
Accept: application/json

###
GET http://localhost:8080/v2.0/api/cursorUsers
Accept: application/json

###
GET http://localhost:8080/v3.0/api/cursorUsers
Accept: application/json

###
GET http://localhost:8080/api/cursorUsers
Accept: application/json

###
GET http://localhost:8080/actuator/mappings
Accept: application/json



